CREATE DATABASE QLSX;
USE QLSX;


CREATE DATABASE QLSX;
GO
USE QLSX;
GO

CREATE TABLE NSX (
    MaNSX NVARCHAR(50) PRIMARY KEY,
    TenNSX NVARCHAR(100),
    DiaChi NVARCHAR(200)
);

CREATE TABLE SP (
    MaSP NVARCHAR(50) PRIMARY KEY,
    MaNSX NVARCHAR(50),
    loai NVARCHAR(50),
    FOREIGN KEY (MaNSX) REFERENCES NSX(MaNSX) ON DELETE CASCADE
);

CREATE TABLE PC (
    MaSP_P NVARCHAR(50) PRIMARY KEY,
    CPU NVARCHAR(50),
    RAM INT,
    HD INT,
    gia DECIMAL(10,2),
    FOREIGN KEY (MaSP_P) REFERENCES SP(MaSP) ON DELETE CASCADE
);

CREATE TABLE Laptop (
    MaSP_L NVARCHAR(50) PRIMARY KEY,
    CPU NVARCHAR(50),
    RAM INT,
    HD INT,
    ManHinh NVARCHAR(50),
    gia DECIMAL(10,2),
    FOREIGN KEY (MaSP_L) REFERENCES SP(MaSP) ON DELETE CASCADE
);

