DELETE FROM NSX WHERE MaNSX NOT IN (SELECT DISTINCT MaNSX FROM SP WHERE loai = 'PC');

SELECT DISTINCT NSX.TenNSX 
FROM NSX 
JOIN SP ON NSX.MaNSX = SP.MaNSX 
WHERE SP.loai = 'Laptop' 
AND NSX.MaNSX NOT IN (SELECT DISTINCT MaNSX FROM SP WHERE loai = 'PC');

UPDATE PC 
SET gia = gia * 1.15 
WHERE MaSP_P IN (SELECT MaSP FROM SP WHERE MaNSX IN (SELECT MaNSX FROM NSX WHERE TenNSX = 'Dell'));

SELECT NSX.TenNSX 
FROM NSX
JOIN SP ON NSX.MaNSX = SP.MaNSX
JOIN PC ON SP.MaSP = PC.MaSP_P
JOIN Laptop ON SP.MaSP = Laptop.MaSP_L
WHERE PC.CPU = Laptop.CPU
GROUP BY NSX.TenNSX
HAVING COUNT(DISTINCT SP.loai) = 2;

SELECT DISTINCT NSX.TenNSX
FROM NSX
JOIN SP ON NSX.MaNSX = SP.MaNSX
LEFT JOIN PC ON SP.MaSP = PC.MaSP_P
LEFT JOIN Laptop ON SP.MaSP = Laptop.MaSP_L
WHERE (PC.HD >= 128 OR PC.HD IS NULL) 
AND (Laptop.HD >= 128 OR Laptop.HD IS NULL);

SELECT NSX.TenNSX
FROM NSX
JOIN SP ON NSX.MaNSX = SP.MaNSX
JOIN PC ON SP.MaSP = PC.MaSP_P
WHERE PC.HD = (SELECT MAX(HD) FROM PC);
